#!/usr/bin/env python
"""DC-NN predictor training.

This module provides the main training infrastructure for DC-NN predictors.

If patient data is unavailable the script falls back to a fully-synthetic
dataset generated by ``dcnn_tube_mpc.synthetic.data_generator`` so the
pipeline can be exercised end-to-end without any private recordings.

Run with:
    python -m dcnn_tube_mpc.training.train_predictor [options]
"""
from __future__ import annotations

import argparse
import logging
import math
import time
from pathlib import Path
from typing import Optional

import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset, random_split

from dcnn_tube_mpc.models.dcnn_models import DCNNModel, MultiStepDCNN, get_device
from dcnn_tube_mpc.models.device_utils import synchronize_device

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Synthetic data fallback
# ---------------------------------------------------------------------------

def _load_or_generate_data(
    data_dir: Optional[Path],
    n_state_y: int = 15,
    n_state_u: int = 15,
    horizon: int = 5,
    n_samples: int = 10000,
    seed: int = 42,
) -> tuple:
    """Load patient data if available, otherwise generate synthetic data.

    Args:
        data_dir: Optional path to directory containing patient recordings.
        n_state_y: Number of past output observations in the state.
        n_state_u: Number of past input observations in the state.
        horizon: Prediction horizon.
        n_samples: Number of synthetic samples to generate if no data found.
        seed: Random seed for synthetic generation.

    Returns:
        Tuple of (X, U, Y) arrays each of shape (n_samples, *).
    """
    if data_dir is not None and data_dir.exists():
        npz_files = list(data_dir.glob("*.npz"))
        if npz_files:
            logger.info("Loading data from %s", data_dir)
            arrays = [np.load(f) for f in npz_files]
            X = np.vstack([a["x"] for a in arrays])
            U = np.vstack([a["u"] for a in arrays])
            Y = np.vstack([a["y"] for a in arrays])
            return X, U, Y

    logger.warning("No patient data found — generating synthetic training data")
    from dcnn_tube_mpc.synthetic.data_generator import generate_modulated_beta, generate_synthetic_stimulation

    n_state = n_state_y + n_state_u
    rng = np.random.default_rng(seed)
    total = n_samples + n_state + horizon + 10

    beta, stim = generate_modulated_beta(total, seed=seed)

    # Build multi-step sequences
    X_list, U_list, Y_list = [], [], []
    for t in range(n_state, len(beta) - horizon):
        x_t = np.hstack([beta[t - n_state_y:t], stim[t - n_state_u:t]])
        u_t = stim[t:t + horizon]
        y_t = beta[t:t + horizon]
        X_list.append(x_t)
        U_list.append(u_t)
        Y_list.append(y_t)
        if len(X_list) >= n_samples:
            break

    X = np.array(X_list, dtype=np.float32)
    U = np.array(U_list, dtype=np.float32)
    Y = np.array(Y_list, dtype=np.float32)
    logger.info("Generated synthetic dataset: %d samples", len(X))
    return X, U, Y


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class OptimizedDBSDataset(Dataset):
    """PyTorch Dataset."""

    def __init__(self, x: np.ndarray, y: np.ndarray):
        self.x = torch.as_tensor(np.ascontiguousarray(x), dtype=torch.float32)
        self.y = torch.as_tensor(np.ascontiguousarray(y), dtype=torch.float32)
        if self.y.ndim == 1:
            self.y = self.y.unsqueeze(1)

    def __len__(self) -> int:
        return len(self.x)

    def __getitem__(self, idx: int):
        return self.x[idx], self.y[idx]


def get_optimal_dataloader_settings(device: torch.device) -> dict:
    """Get optimal DataLoader settings for the given device."""
    settings = {
        "num_workers": 2,
        "persistent_workers": True,
        "prefetch_factor": 2,
    }

    if device.type == "cuda":
        settings["pin_memory"] = True
    elif device.type == "mps":
        settings["pin_memory"] = False
        settings["num_workers"] = 0
        settings["persistent_workers"] = False
    else:
        settings["pin_memory"] = False

    return settings


def create_optimized_dataloaders(
    x: np.ndarray,
    y: np.ndarray,
    batch_size: int = 512,
    val_split: float = 0.2,
    num_workers: int = None,
    pin_memory: bool = None,
    device: torch.device = None,
):
    """Create DataLoaders with device-optimized settings.

    Args:
        x: Input features
        y: Target values
        batch_size: Batch size
        val_split: Validation split fraction
        num_workers: Number of worker processes (None=auto-detect)
        pin_memory: Pin memory for faster GPU transfers (None=auto-detect)
        device: Target device

    Returns:
        Tuple of (train_loader, val_loader)
    """
    if device is None:
        device = get_device()

    optimal = get_optimal_dataloader_settings(device)
    if num_workers is None:
        num_workers = optimal["num_workers"]
    if pin_memory is None:
        pin_memory = optimal["pin_memory"]

    dataset = OptimizedDBSDataset(x, y)
    val_size = int(len(dataset) * val_split)
    train_size = len(dataset) - val_size

    train_ds, val_ds = random_split(
        dataset,
        [train_size, val_size],
        generator=torch.Generator().manual_seed(42),
    )

    train_loader = DataLoader(
        train_ds,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=pin_memory,
        persistent_workers=num_workers > 0,
        drop_last=True,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
        persistent_workers=num_workers > 0,
    )

    return train_loader, val_loader


def train_single_network_optimized(
    model: DCNNModel,
    train_loader: DataLoader,
    val_loader: DataLoader,
    epochs: int = 100,
    lr: float = 0.001,
    device: torch.device = None,
    verbose: int = 1,
    optimizer_type: str = "adam",
    use_warmup: bool = True,
    use_cosine_decay: bool = True,
    warmup_epochs: int = 5,
    early_stopping: bool = True,
    early_stopping_patience: int = 10,
    early_stopping_min_delta: float = 1e-5,
    criterion=None,
):
    """Train a single DC-NN.

    Args:
        model: DC-NN model to train.
        train_loader: Training DataLoader.
        val_loader: Validation DataLoader.
        epochs: Maximum training epochs.
        lr: Learning rate.
        device: Target device.
        verbose: Verbosity level (0=silent, 1=per-10-epochs, 2=per-epoch).
        optimizer_type: "rmsprop", "adam", or "adamw".
        use_warmup: Use learning rate warmup.
        use_cosine_decay: Use cosine annealing LR decay.
        warmup_epochs: Number of warmup epochs.
        early_stopping: Enable early stopping based on validation loss.
        early_stopping_patience: Stop if no improvement for this many epochs.
        early_stopping_min_delta: Minimum improvement to count as progress.
        criterion: Loss function (default: MSELoss).

    Returns:
        Training history dict.
    """
    if device is None:
        device = get_device()

    if device.type == "cuda":
        torch.backends.cudnn.benchmark = True
        torch.set_float32_matmul_precision("high")

    model = model.to(device)

    if optimizer_type == "adam":
        optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    elif optimizer_type == "adamw":
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=0.01)
    else:
        optimizer = torch.optim.RMSprop(model.parameters(), lr=lr)

    scheduler = None
    if use_cosine_decay:
        if use_warmup:
            def lr_lambda(epoch):
                if epoch < warmup_epochs:
                    return (epoch + 1) / warmup_epochs
                else:
                    progress = (epoch - warmup_epochs) / max(1, epochs - warmup_epochs)
                    return 0.5 * (1 + math.cos(math.pi * progress))
            scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)
        else:
            scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    if criterion is None:
        criterion = torch.nn.MSELoss()

    history = {"loss": [], "val_loss": [], "mae": [], "val_mae": []}
    best_val_loss = float("inf")
    best_model_state = None
    patience_counter = 0
    stopped_epoch = None

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        train_mae = 0.0
        n_train = 0

        for x_batch, y_batch in train_loader:
            x_batch = x_batch.to(device, non_blocking=True)
            y_batch = y_batch.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)
            pred = model(x_batch)
            loss = criterion(pred, y_batch)
            loss.backward()
            optimizer.step()
            model.enforce_constraints()

            batch_size = x_batch.size(0)
            train_loss += loss.item() * batch_size
            train_mae += torch.abs(pred - y_batch).sum().item()
            n_train += batch_size

        train_loss /= n_train
        train_mae /= n_train

        model.eval()
        val_loss = 0.0
        val_mae = 0.0
        n_val = 0

        with torch.no_grad():
            for x_batch, y_batch in val_loader:
                x_batch = x_batch.to(device, non_blocking=True)
                y_batch = y_batch.to(device, non_blocking=True)

                pred = model(x_batch)
                loss = criterion(pred, y_batch)

                batch_size = x_batch.size(0)
                val_loss += loss.item() * batch_size
                val_mae += torch.abs(pred - y_batch).sum().item()
                n_val += batch_size

        val_loss /= n_val
        val_mae /= n_val

        history["loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["mae"].append(train_mae)
        history["val_mae"].append(val_mae)

        if verbose >= 2 or (verbose >= 1 and (epoch + 1) % 10 == 0):
            print(
                f"  Epoch {epoch + 1}/{epochs} - "
                f"loss: {train_loss:.6f} - mae: {train_mae:.6f} - "
                f"val_loss: {val_loss:.6f} - val_mae: {val_mae:.6f}"
            )

        if scheduler:
            scheduler.step()

        if early_stopping:
            if val_loss < best_val_loss - early_stopping_min_delta:
                best_val_loss = val_loss
                best_model_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                patience_counter = 0
            else:
                patience_counter += 1
                if patience_counter >= early_stopping_patience:
                    stopped_epoch = epoch + 1
                    if verbose >= 1:
                        print(f"  Early stopping at epoch {stopped_epoch} "
                              f"(best val_loss: {best_val_loss:.6f})")
                    break

    if early_stopping and best_model_state is not None:
        model.load_state_dict(best_model_state)
        model.to(device)

    history["stopped_epoch"] = stopped_epoch
    history["best_val_loss"] = best_val_loss if early_stopping else None

    return history


class MultiStepPredictor:
    """GPU-optimized multi-step DC-NN predictor.

    Provides a unified interface for training and using multi-step DC-NN
    predictors, compatible with the CDC25 pipeline.
    """

    def __init__(
        self,
        n_state: int = 30,
        n_input: int = 1,
        n_hidden: int = 32,
        n_layers: int = 1,
        horizon: int = 5,
        device: torch.device = None,
        use_spectral_norm: bool = False,
        spectral_norm_target: float = 0.5,
        spectral_norm_n_power_iterations: int = 1,
        spectral_norm_layers: str = "all",
        log_space: bool = False,
        n_state_y: int = 15,
        sample_rate: int = 50,
    ):
        self.n_state = n_state
        self.n_input = n_input
        self.n_hidden = n_hidden
        self.n_layers = n_layers
        self.horizon = horizon
        self.device = device if device is not None else get_device()
        self.use_spectral_norm = use_spectral_norm
        self.spectral_norm_target = spectral_norm_target
        self.spectral_norm_n_power_iterations = spectral_norm_n_power_iterations
        self.spectral_norm_layers = spectral_norm_layers
        self.log_space = log_space
        self.n_state_y = n_state_y
        self.n_state_u = n_state - n_state_y
        self.sample_rate = sample_rate
        self.dt = 1.0 / sample_rate

        self.model = MultiStepDCNN(
            n_state=n_state,
            n_input=n_input,
            n_hidden=n_hidden,
            n_layers=n_layers,
            horizon=horizon,
            use_spectral_norm=use_spectral_norm,
            spectral_norm_target=spectral_norm_target,
            spectral_norm_n_power_iterations=spectral_norm_n_power_iterations,
            spectral_norm_layers=spectral_norm_layers,
        ).to(self.device)

        self.histories = []

    def train(
        self,
        x: np.ndarray,
        u: np.ndarray,
        y: np.ndarray,
        epochs: int = 100,
        batch_size: int = 512,
        lr: float = 0.001,
        val_split: float = 0.2,
        num_workers: int = 2,
        pin_memory: bool = True,
        verbose: int = 1,
        optimizer_type: str = "adam",
        use_warmup: bool = True,
        use_cosine_decay: bool = True,
        early_stopping: bool = False,
        early_stopping_patience: int = 10,
        early_stopping_min_delta: float = 1e-5,
    ):
        """Train all N networks.

        Args:
            x: State sequences (n_samples, n_state)
            u: Control sequences (n_samples, horizon)
            y: Target sequences (n_samples, horizon)
            epochs: Training epochs per network
            batch_size: Batch size
            lr: Learning rate
            val_split: Validation split fraction
            num_workers: DataLoader worker processes
            pin_memory: Pin memory for faster GPU transfers
            verbose: Verbosity level
            optimizer_type: "rmsprop", "adam", or "adamw"
            use_warmup: Use learning rate warmup
            use_cosine_decay: Use cosine annealing LR decay
            early_stopping: Enable early stopping
            early_stopping_patience: Patience epochs
            early_stopping_min_delta: Minimum improvement threshold

        Returns:
            Dict with training summary
        """
        self.histories = []
        start_time = time.time()

        print(f"\nTraining {self.horizon} networks on {self.device}")
        print(f"  Batch size: {batch_size}, Max epochs: {epochs}, LR: {lr}")
        print(f"  Optimizer: {optimizer_type}, Samples: {len(x):,}")

        for k in range(1, self.horizon + 1):
            if verbose >= 1:
                print(f"Training network k={k}/{self.horizon}...")

            x_k = np.hstack([x, u[:, :k]])
            y_k = y[:, k - 1]

            train_loader, val_loader = create_optimized_dataloaders(
                x_k, y_k,
                batch_size=batch_size,
                val_split=val_split,
                num_workers=num_workers,
                pin_memory=pin_memory,
            )

            network_k = self.model.networks[k - 1]
            history = train_single_network_optimized(
                network_k,
                train_loader,
                val_loader,
                epochs=epochs,
                lr=lr,
                device=self.device,
                verbose=verbose - 1,
                optimizer_type=optimizer_type,
                use_warmup=use_warmup,
                use_cosine_decay=use_cosine_decay,
                early_stopping=early_stopping,
                early_stopping_patience=early_stopping_patience,
                early_stopping_min_delta=early_stopping_min_delta,
            )
            self.histories.append(history)

            if verbose >= 1:
                final_loss = history["val_loss"][-1]
                final_mae = history["val_mae"][-1]
                stopped_info = ""
                if history.get("stopped_epoch"):
                    stopped_info = f", stopped at epoch {history['stopped_epoch']}"
                print(f"  -> val_loss={final_loss:.6f}, val_mae={final_mae:.6f}{stopped_info}\n")

        elapsed = time.time() - start_time
        synchronize_device(self.device)

        actual_epochs = [
            h.get("stopped_epoch") or len(h["val_loss"])
            for h in self.histories
        ]

        return {
            "elapsed_time": elapsed,
            "max_epochs": epochs,
            "actual_epochs": actual_epochs,
            "batch_size": batch_size,
            "n_networks": self.horizon,
            "final_val_losses": [h["val_loss"][-1] for h in self.histories],
            "device": str(self.device),
        }

    def save(self, save_dir: Path):
        """Save model weights and training history."""
        self.save_models(save_dir)

    def save_models(self, save_dir: Path):
        """Save model weights and training history.

        Args:
            save_dir: Directory to save model files
        """
        import json
        save_dir = Path(save_dir)
        save_dir.mkdir(parents=True, exist_ok=True)

        config = {
            "n_state": self.n_state,
            "n_state_y": self.n_state_y,
            "n_state_u": self.n_state_u,
            "n_input": self.n_input,
            "n_hidden": self.n_hidden,
            "n_layers": self.n_layers,
            "horizon": self.horizon,
            "backend": "pytorch",
            "sample_rate": self.sample_rate,
            "dt": self.dt,
            "use_spectral_norm": self.use_spectral_norm,
            "spectral_norm_target": self.spectral_norm_target,
            "spectral_norm_n_power_iterations": self.spectral_norm_n_power_iterations,
            "spectral_norm_layers": self.spectral_norm_layers,
            "log_space": self.log_space,
        }
        with open(save_dir / "config.json", "w") as f:
            json.dump(config, f, indent=2)

        for k in range(1, self.horizon + 1):
            network_path = save_dir / f"network_k{k}.pt"
            torch.save(self.model.networks[k - 1].state_dict(), network_path)

        if self.histories:
            histories_data = {f"k{k}": h for k, h in enumerate(self.histories, start=1)}
            with open(save_dir / "training_histories.json", "w") as f:
                json.dump(histories_data, f, indent=2)

        print(f"Saved model to {save_dir}")

    def load_models(self, load_dir: Path):
        """Load model weights from directory.

        Args:
            load_dir: Directory containing saved model files
        """
        import json
        load_dir = Path(load_dir)

        config_path = load_dir / "config.json"
        saved_use_sn = False
        if config_path.exists():
            with open(config_path) as f:
                config = json.load(f)
            if config.get("horizon", self.horizon) != self.horizon:
                raise ValueError(
                    f"Horizon mismatch: model has {config['horizon']}, "
                    f"but predictor expects {self.horizon}"
                )
            saved_use_sn = config.get("use_spectral_norm", False)
            self.log_space = config.get("log_space", False)

        for k in range(1, self.horizon + 1):
            network_path = load_dir / f"network_k{k}.pt"
            if not network_path.exists():
                raise FileNotFoundError(f"Network weights not found: {network_path}")

            state_dict = torch.load(network_path, map_location=self.device, weights_only=True)
            network = self.model.networks[k - 1]

            if self.use_spectral_norm and not saved_use_sn:
                state_dict = self._convert_to_sn_state_dict(state_dict, network)
            elif not self.use_spectral_norm and saved_use_sn:
                state_dict = self._convert_from_sn_state_dict(state_dict)

            network.load_state_dict(state_dict, strict=False)

        self.model.to(self.device)
        print(f"Loaded model from {load_dir}")

    def _convert_to_sn_state_dict(self, state_dict: dict, network) -> dict:
        """Convert non-SN state dict to SN format."""
        new_state_dict = {}
        for key, value in state_dict.items():
            if ".weight" in key and not key.endswith("_orig"):
                parts = key.split(".")
                if len(parts) >= 2:
                    new_key = key.replace(".weight", ".module.weight_orig")
                    new_state_dict[new_key] = value
                    new_state_dict[key] = value
            else:
                new_state_dict[key] = value
        return new_state_dict

    def _convert_from_sn_state_dict(self, state_dict: dict) -> dict:
        """Convert SN state dict to non-SN format."""
        new_state_dict = {}
        for key, value in state_dict.items():
            if "weight_orig" in key:
                new_key = key.replace(".module.weight_orig", ".weight")
                new_key = new_key.replace(".weight_orig", ".weight")
                new_state_dict[new_key] = value
            elif ".module." in key:
                new_key = key.replace(".module.", ".")
                new_state_dict[new_key] = value
            elif "_u" not in key and "_v" not in key:
                new_state_dict[key] = value
        return new_state_dict

    def build_models(self):
        """Build models (no-op, models are built in __init__)."""
        pass

    @property
    def networks(self):
        """Get underlying network list for compatibility."""
        return self.model.networks


def main():
    parser = argparse.ArgumentParser(
        description="DC-NN predictor training",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--lr", type=float, default=0.001)
    parser.add_argument("--n-hidden", type=int, default=32)
    parser.add_argument("--n-layers", type=int, default=1)
    parser.add_argument("--horizon", type=int, default=5)
    parser.add_argument("--n-state-y", type=int, default=15)
    parser.add_argument("--n-state-u", type=int, default=15)
    parser.add_argument("--data-dir", type=Path, default=None)
    parser.add_argument("--save-dir", type=Path, default=Path("models/dcnn"))
    parser.add_argument("--n-samples", type=int, default=20000,
                        help="Synthetic samples if no data-dir provided")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    n_state = args.n_state_y + args.n_state_u
    X, U, Y = _load_or_generate_data(
        data_dir=args.data_dir,
        n_state_y=args.n_state_y,
        n_state_u=args.n_state_u,
        horizon=args.horizon,
        n_samples=args.n_samples,
    )

    predictor = MultiStepPredictor(
        n_state=n_state,
        n_hidden=args.n_hidden,
        n_layers=args.n_layers,
        horizon=args.horizon,
        n_state_y=args.n_state_y,
    )

    predictor.train(
        x=X,
        u=U,
        y=Y,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        verbose=1,
    )

    predictor.save_models(args.save_dir)
    print("Training complete.")


if __name__ == "__main__":
    main()
